#!/usr/bin/env python3
"""Generate the "supported platforms" table in the package README (decision #53).

Authoritative source: the binaries **tracked by git**, not the ones on disk.

That distinction is the whole point. Plugin binaries are currently gitignored
until a batch lands (#35), so a working tree that has just been built has a
macOS binary while a fresh clone has none. Keying off the filesystem would make
this table differ between a developer's machine and CI, and the CI diff would
be permanently red -- the same trap that the orphan-.meta rule fell into.

What git tracks is exactly what an adopter receives, so it is both stable and
the honest answer to "which platforms does this package ship?".

The table therefore cannot lie: it is derived from the artifacts themselves.
Nobody maintains a list by hand, so nobody can forget to update one (#53).

Also enforced here, because this script already walks the landed artifacts:

    every landed binary must sit next to a build-info.json that came from CI.

A build-info.json with `ci: null` was produced by someone's local build; it
records a dirty worktree and no run URL, so it has no provenance value at all
(#54). Landing one would leave a binary nobody can trace.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_plugin_meta import PLATFORMS  # noqa: E402  单一平台清单，不在这里重复一份


def _force_utf8_output() -> None:
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            reconfigure(encoding="utf-8")


_force_utf8_output()

BEGIN = "<!-- BEGIN supported-platforms (generated by native/scripts/gen_support_table.py) -->"
END = "<!-- END supported-platforms -->"

# Display metadata, keyed by the same relative paths as gen_plugin_meta.PLATFORMS.
# The keys are cross-checked against that map below, so the two cannot drift:
# adding a platform there without adding it here is a hard failure, not a
# silently missing table row.
DISPLAY = {
    "Windows/x86_64/datachannel_unity.dll": ("Windows", "x86_64", "Editor + Player"),
    "macOS/datachannel_unity.dylib": ("macOS", "universal (arm64 + x86_64)", "Editor + Player"),
    "Linux/x86_64/libdatachannel_unity.so": ("Linux", "x86_64", "Editor + Player"),
    "Android/arm64-v8a/libdatachannel_unity.so": ("Android", "arm64-v8a", "Player only"),
    "iOS/libdatachannel_unity.a": ("iOS", "arm64", "Player only"),
}


class SupportTableError(Exception):
    pass


def tracked_files(repo_root: Path, plugin_root: Path) -> set[str]:
    rel = plugin_root.resolve().relative_to(repo_root.resolve())
    proc = subprocess.run(["git", "-C", str(repo_root), "ls-files", str(rel)],
                          capture_output=True, text=True)
    if proc.returncode != 0:
        raise SupportTableError(
            "git ls-files failed, so the set of shipped binaries cannot be determined.\n"
            f"  {proc.stderr.strip()}\n"
            "  This script keys off what git tracks on purpose; guessing from the\n"
            "  filesystem would make the table differ between a built worktree and a\n"
            "  fresh clone.")
    prefix = str(rel).replace("\\", "/") + "/"
    return {line[len(prefix):] for line in proc.stdout.splitlines()
            if line.replace("\\", "/").startswith(prefix)}


def is_landed(rel: str, tracked: set[str]) -> bool:
    """Is this platform's artifact tracked by git?

    Every artifact is a single file today, so plain equality would do. The
    prefix branch stays because it once did not: macOS shipped a `.bundle`,
    a **directory**, and git tracks the files inside it rather than the
    directory itself -- exact matching silently reported "not landed" for
    macOS forever. The bundle is gone (see stage_plugin.py), but a directory
    artifact can come back (an iOS `.framework`, say), and this branch costs
    one line.
    """
    return rel in tracked or any(t.startswith(rel + "/") for t in tracked)


def check_build_info(tracked: set[str], landed: list[str],
                     plugin_root: Path) -> list[str]:
    """Every landed binary needs a CI-produced build-info.json beside it."""
    problems = []
    for rel in landed:
        sibling = str(Path(rel).parent / "build-info.json").replace("\\", "/")
        if sibling not in tracked:
            problems.append(f"  {rel}: no build-info.json is tracked beside it "
                            f"(expected {sibling})")
            continue
        path = plugin_root / sibling
        try:
            info = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            problems.append(f"  {sibling}: cannot be read as JSON ({exc})")
            continue
        ci = info.get("ci")
        if not ci:
            problems.append(
                f"  {sibling}: ci is null, so this came from a local build. "
                "Land the CI-produced file instead -- a local one records a dirty "
                "worktree and no run URL, so it has no provenance value.")
            continue
        if ci.get("event") == "pull_request":
            problems.append(
                f"  {sibling}: built by a `pull_request` run, so source.commit "
                f"({info.get('source', {}).get('commit', '?')[:9]}) is GitHub's synthetic "
                "merge ref -- that SHA stops existing once the PR is merged, and the "
                "binary becomes untraceable. Land artifacts from a push-to-main run or "
                "from plugins-matrix.yml (dispatch / schedule / release) instead.")
    return problems


def render(landed: list[str]) -> str:
    lines = [BEGIN, ""]
    if not landed:
        lines += [
            "This package currently ships **no platform binaries**.",
            "",
            "They land in batches, each after that platform passes CI plus a real-device",
            "smoke test. Building for any platform will stop with an explicit error rather",
            "than producing a player that fails at runtime.",
        ]
    else:
        lines += [
            "| Platform | Architecture | Loaded by |",
            "|---|---|---|",
        ]
        for rel in landed:
            name, arch, where = DISPLAY[rel]
            lines.append(f"| {name} | {arch} | {where} |")
        missing = [r for r in PLATFORMS if r not in landed]
        if missing:
            lines += ["", "Not shipped yet: "
                      + ", ".join(DISPLAY[r][0] + " " + DISPLAY[r][1] for r in missing)
                      + ". Building for those targets stops with an explicit error."]
    lines += ["", END]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate the supported-platforms table")
    ap.add_argument("--repo-root", required=True, type=Path)
    ap.add_argument("--plugin-root", required=True, type=Path)
    ap.add_argument("--readme", required=True, type=Path)
    ap.add_argument("--check", action="store_true",
                    help="check only, never write; exit non-zero on any difference (for CI)")
    args = ap.parse_args()

    unknown = set(DISPLAY) ^ set(PLATFORMS)
    if unknown:
        raise SupportTableError(
            "DISPLAY and gen_plugin_meta.PLATFORMS disagree: " + ", ".join(sorted(unknown))
            + "\n  They must list exactly the same platforms. Adding one to the meta\n"
              "  generator without adding it here would silently drop a table row.")

    tracked = tracked_files(args.repo_root, args.plugin_root)
    landed = [rel for rel in PLATFORMS if is_landed(rel, tracked)]

    problems = check_build_info(tracked, landed, args.plugin_root)
    if problems:
        raise SupportTableError(
            "Landed binaries without usable provenance (#54):\n" + "\n".join(problems))

    if not args.readme.is_file():
        raise SupportTableError(f"Missing {args.readme}")
    text = args.readme.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise SupportTableError(
            f"{args.readme} has no generated-table markers.\n"
            f"  Insert these two lines where the table belongs:\n    {BEGIN}\n    {END}")

    head, _, rest = text.partition(BEGIN)
    _, _, tail = rest.partition(END)
    updated = head + render(landed) + tail

    if updated == text:
        print(f"OK: the support table lists {len(landed)}/{len(PLATFORMS)} platform(s) "
              "and is up to date")
        return 0

    if args.check:
        raise SupportTableError(
            "The support table in the README is stale.\n"
            "  Fix: run native/scripts/gen_support_table.py without --check and commit the diff.\n"
            "  The table is derived from the binaries git tracks, so it cannot be\n"
            "  maintained by hand -- and therefore cannot silently go out of date.")

    args.readme.write_text(updated, encoding="utf-8")
    print(f"wrote the support table into {args.readme} "
          f"({len(landed)}/{len(PLATFORMS)} platform(s) shipped)")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except SupportTableError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
