#!/usr/bin/env python3
"""Generate the "supported platforms" table in the package README (decision #53).

Authoritative source: the binaries **tracked by git**, not the ones on disk.

That distinction is the whole point. Plugin binaries are currently gitignored
until a batch lands (#35), so a working tree that has just been built has a
macOS binary while a fresh clone has none. Keying off the filesystem would make
this table differ between a developer's machine and CI, and the CI diff would
be permanently red -- the same trap that the orphan-.meta rule fell into.

What git tracks is exactly what an adopter receives, so it is both stable and
the honest answer to "which platforms does this package ship?".

The table therefore cannot lie: it is derived from the artifacts themselves.
Nobody maintains a list by hand, so nobody can forget to update one (#53).

Also enforced here, because this script already walks the landed artifacts:

    every landed binary must have a CI-produced provenance file in `Report~/`.
    every landed binary must have an unstripped twin under `Symbols~/` (same
    relative path; Windows also needs the `.pdb`). The check runs only when
    `--symbols-root` is passed — it is added in the same commit that lands
    the first `Symbols~/` files, otherwise this gate would be permanently red.

A build-info file with `ci: null` was produced by someone's local build: no run
URL, and a commit that describes the checkout rather than what was compiled, so
it has no provenance value at all (#54). Landing one would leave a binary nobody
can trace. `ci` is the whole test -- a CI record is a fresh checkout of
`source.commit`, so nothing further needs asserting about the tree it came from
(#68 deleted the `dirty` field that used to imply otherwise).

#65 moved those files out of `Plugins/` and into `Report~/<flattened>.json`,
which changes only where this gate looks -- **not what it can prove**. The
point of #54's "beside the binary" was never convenience; it was that
"binary landed, provenance did not" must have nowhere to hide. That survives
intact, because the expected file name is still computed from the binary's own
path (`gen_plugin_meta.report_name`). There is no hand-maintained mapping here
that could be quietly edited to make a missing file look present.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_plugin_meta import PLATFORMS, report_name  # noqa: E402  单一平台清单与拍平名推导


def _force_utf8_output() -> None:
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            reconfigure(encoding="utf-8")


_force_utf8_output()

BEGIN = "<!-- BEGIN supported-platforms (generated by native/scripts/gen_support_table.py) -->"
END = "<!-- END supported-platforms -->"

# Display metadata, keyed by the same relative paths as gen_plugin_meta.PLATFORMS.
# The keys are cross-checked against that map below, so the two cannot drift:
# adding a platform there without adding it here is a hard failure, not a
# silently missing table row.
DISPLAY = {
    "Windows/x86_64/datachannel_unity.dll": ("Windows", "x86_64", "Editor + Player"),
    "macOS/datachannel_unity.dylib": ("macOS", "universal (arm64 + x86_64)", "Editor + Player"),
    "Linux/x86_64/libdatachannel_unity.so": ("Linux", "x86_64", "Editor + Player"),
    "Android/arm64-v8a/libdatachannel_unity.so": ("Android", "arm64-v8a", "Player only"),
    "iOS/libdatachannel_unity.a": ("iOS", "arm64", "Player only"),
}


class SupportTableError(Exception):
    pass


def tracked_files(repo_root: Path, directory: Path) -> set[str]:
    """Paths git tracks under `directory`, relative to it.

    Called twice: once for `Plugins/` (which binaries shipped) and once for
    `Report~/` (which provenance files shipped). An untracked-but-present file
    counts as absent in both, which is the point -- what git tracks is exactly
    what an adopter receives.
    """
    rel = directory.resolve().relative_to(repo_root.resolve())
    proc = subprocess.run(["git", "-C", str(repo_root), "ls-files", str(rel)],
                          capture_output=True, text=True)
    if proc.returncode != 0:
        raise SupportTableError(
            f"git ls-files failed for {rel}, so what this package ships cannot be "
            "determined.\n"
            f"  {proc.stderr.strip()}\n"
            "  This script keys off what git tracks on purpose; guessing from the\n"
            "  filesystem would make the table differ between a built worktree and a\n"
            "  fresh clone.")
    prefix = str(rel).replace("\\", "/") + "/"
    return {line[len(prefix):] for line in proc.stdout.splitlines()
            if line.replace("\\", "/").startswith(prefix)}


def is_landed(rel: str, tracked: set[str]) -> bool:
    """Is this platform's artifact tracked by git?

    Every artifact is a single file today, so plain equality would do. The
    prefix branch stays because it once did not: macOS shipped a `.bundle`,
    a **directory**, and git tracks the files inside it rather than the
    directory itself -- exact matching silently reported "not landed" for
    macOS forever. The bundle is gone (see stage_plugin.py), but a directory
    artifact can come back (an iOS `.framework`, say), and this branch costs
    one line.
    """
    return rel in tracked or any(t.startswith(rel + "/") for t in tracked)


# What a real artifact starts with, keyed by the extension git actually stores.
# A Git LFS pointer is ASCII text beginning "version https://git-lfs...", so any
# of these magics is enough to tell the two apart.
BINARY_MAGIC = {
    ".dll": (b"MZ",),                       # PE
    ".so": (b"\x7fELF",),                   # ELF
    ".dylib": (b"\xcf\xfa\xed\xfe",         # Mach-O 64 LE (thin)
               b"\xca\xfe\xba\xbe",         # universal (fat), big-endian magic
               b"\xbe\xba\xfe\xca"),        # universal, byte-swapped
    ".a": (b"!<arch>",),                    # ar archive
    ".pdb": (b"Microsoft C/C++",            # MSVC PDB 7.0 (MSF)
             b"BSJB"),                      # portable PDB
}

LFS_POINTER_PREFIX = b"version https://git-lfs"


def check_binary_blobs(repo_root: Path, plugin_root: Path, landed: list[str]) -> list[str]:
    """Every landed binary must be a **real binary in git**, not an LFS pointer.

    This gate exists because the failure it catches actually shipped. v0.1.0's
    binaries were tracked, audited, `.meta`-checked and listed in the support
    table -- and every one of them was a 132-byte text file in git, because the
    repository-root `.gitattributes` routed `*.dll` / `*.so` through Git LFS.
    Installing the package from a Git URL got the pointer, and Unity reported
    "expected x64 architecture, but was Unknown architecture".

    Nothing else here could have seen it. Every other check reads the file **on
    disk**, where a developer's LFS smudge filter has already replaced the
    pointer with the real bytes; the audit even passes, because it audits a
    freshly built artifact rather than the landed one. The only place the truth
    lives is the blob git stores, so that is what this reads -- via `git show`,
    never the working tree.

    Deliberately a positive assertion about the content, not "is the filter
    attribute unset": an attribute check would pass on an empty file, a
    truncated one, or a `.dll` that is secretly a shell script. Assert what the
    artifact **is**, not how it was configured.
    """
    problems = []
    for rel in landed:
        path = (plugin_root / rel)
        suffix = path.suffix.lower()
        magics = BINARY_MAGIC.get(suffix)
        if magics is None:
            problems.append(
                f"  {rel}: no magic number is known for '{suffix}'. Add one to "
                "BINARY_MAGIC -- an unknown extension must not silently skip this gate.")
            continue
        git_path = path.resolve().relative_to(repo_root.resolve()).as_posix()
        proc = subprocess.run(["git", "-C", str(repo_root), "show", f"HEAD:{git_path}"],
                              capture_output=True)
        if proc.returncode != 0:
            problems.append(f"  {rel}: cannot read the blob git stores "
                            f"({proc.stderr.decode('utf-8', 'replace').strip()})")
            continue
        # PDB's MSF header is longer than ELF/PE/Mach-O magics; slicing to 8
        # bytes made `Microsoft C/C++` look like a mismatch (`b'Microsof'`).
        head = proc.stdout[:max(len(m) for m in magics)]
        if any(head.startswith(m) for m in magics):
            continue
        if proc.stdout.startswith(LFS_POINTER_PREFIX):
            problems.append(
                f"  {rel}: git stores a **Git LFS pointer**, not the binary.\n"
                "      An adopter installing from a Git URL receives that text file, and\n"
                "      Unity reports 'Unknown architecture' -- this is exactly how v0.1.0\n"
                "      shipped broken. Plugin binaries must not be LFS-tracked (SPEC §10).\n"
                "      Fix: check `.gitattributes` really unsets the filter for this path\n"
                "      (`-filter`; the `binary` macro alone does NOT), then re-add the file:\n"
                f"        git rm --cached {git_path} && git add {git_path}")
        else:
            problems.append(
                f"  {rel}: git stores something that is not a {suffix} "
                f"(first bytes: {head!r}).")
    return problems


def check_symbols(repo_root: Path, symbols_root: Path, landed: list[str]) -> list[str]:
    """Every landed Plugins/ binary has a twin under Symbols~/ at the same rel path.

    Same pairing trick as Report~: the expected path is derived from the binary
    itself, so there is no hand-maintained mapping that could lie. Windows is
    the one extra file — crash tools want the PDB, which never lives in
    Plugins/.
    """
    tracked = tracked_files(repo_root, symbols_root)
    problems = []
    missing = [rel for rel in landed if not is_landed(rel, tracked)]
    for rel in missing:
        problems.append(
            f"  {rel}: no twin under {symbols_root.name}/ "
            f"(expected {symbols_root.name}/{rel})")
    present = [rel for rel in landed if is_landed(rel, tracked)]
    problems.extend(check_binary_blobs(repo_root, symbols_root, present))
    pdb_rels = []
    for rel in landed:
        if Path(rel).suffix.lower() != ".dll":
            continue
        pdb = Path(rel).with_suffix(".pdb").as_posix()
        if not is_landed(pdb, tracked):
            problems.append(
                f"  {rel}: Windows crash tools need {symbols_root.name}/{pdb} "
                "beside the dll (the PDB never ships in Plugins/)")
        else:
            pdb_rels.append(pdb)
    if pdb_rels:
        problems.extend(check_binary_blobs(repo_root, symbols_root, pdb_rels))
    return problems


def check_build_info(tracked_reports: set[str], landed: list[str],
                     report_root: Path) -> list[str]:
    """Every landed binary needs a CI-produced provenance file in `Report~/`."""
    problems = []
    for rel in landed:
        # Derived from the binary's own path, so no list exists that could lie.
        name = report_name(Path(rel).parent.as_posix())
        if name not in tracked_reports:
            problems.append(f"  {rel}: no provenance file is tracked for it "
                            f"(expected {report_root.name}/{name})")
            continue
        path = report_root / name
        try:
            info = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            problems.append(f"  {name}: cannot be read as JSON ({exc})")
            continue
        ci = info.get("ci")
        if not ci:
            problems.append(
                f"  {name}: ci is null, so this came from a local build. "
                "Land the CI-produced file instead -- a local one has no run URL, "
                "and its commit describes the checkout rather than what was "
                "compiled, so it has no provenance value.")
            continue
        if ci.get("event") == "pull_request":
            problems.append(
                f"  {name}: built by a `pull_request` run, so source.commit "
                f"({info.get('source', {}).get('commit', '?')[:9]}) is GitHub's synthetic "
                "merge ref -- that SHA stops existing once the PR is merged, and the "
                "binary becomes untraceable. Land artifacts from a push-to-main run or "
                "from plugins-matrix.yml (dispatch / schedule / release) instead.")
    return problems


def render(landed: list[str], report_dirname: str) -> str:
    """The table also names each platform's provenance file, for the same reason
    the platform rows are generated at all (#53): a hand-written "where is the
    build record for my platform" list is one more thing that goes stale the day
    a platform lands and nobody remembers to edit the README. The file name comes
    from the same `report_name` the gate uses, so the column cannot point at a
    file that is not the one being checked.
    """
    lines = [BEGIN, ""]
    if not landed:
        lines += [
            "This package currently ships **no platform binaries**.",
            "",
            "They land in batches, each after that platform passes CI plus a real-device",
            "smoke test. Building for any platform will stop with an explicit error rather",
            "than producing a player that fails at runtime.",
        ]
    else:
        lines += [
            "| Platform | Architecture | Loaded by | Build record |",
            "|---|---|---|---|",
        ]
        for rel in landed:
            name, arch, where = DISPLAY[rel]
            record = report_name(Path(rel).parent.as_posix())
            lines.append(f"| {name} | {arch} | {where} | `{report_dirname}/{record}` |")
        missing = [r for r in PLATFORMS if r not in landed]
        if missing:
            lines += ["", "Not shipped yet: "
                      + ", ".join(DISPLAY[r][0] + " " + DISPLAY[r][1] for r in missing)
                      + ". Building for those targets stops with an explicit error."]
    lines += ["", END]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate the supported-platforms table")
    ap.add_argument("--repo-root", required=True, type=Path)
    ap.add_argument("--plugin-root", required=True, type=Path)
    ap.add_argument("--report-root", required=True, type=Path,
                    help="Packages/datachannel-unity/Report~ -- where the provenance "
                         "files live since #65")
    ap.add_argument("--symbols-root", type=Path, default=None,
                    help="Packages/datachannel-unity/Symbols~ -- unstripped twins "
                         "(optional until the first Symbols~/ batch lands)")
    ap.add_argument("--readme", required=True, type=Path)
    ap.add_argument("--check", action="store_true",
                    help="check only, never write; exit non-zero on any difference (for CI)")
    args = ap.parse_args()

    unknown = set(DISPLAY) ^ set(PLATFORMS)
    if unknown:
        raise SupportTableError(
            "DISPLAY and gen_plugin_meta.PLATFORMS disagree: " + ", ".join(sorted(unknown))
            + "\n  They must list exactly the same platforms. Adding one to the meta\n"
              "  generator without adding it here would silently drop a table row.")

    tracked = tracked_files(args.repo_root, args.plugin_root)
    landed = [rel for rel in PLATFORMS if is_landed(rel, tracked)]

    problems = check_binary_blobs(args.repo_root, args.plugin_root, landed)
    if problems:
        raise SupportTableError(
            "Landed artifacts that are not the binary they claim to be:\n"
            + "\n".join(problems))

    problems = check_build_info(tracked_files(args.repo_root, args.report_root),
                                landed, args.report_root)
    if problems:
        raise SupportTableError(
            "Landed binaries without usable provenance (#54):\n" + "\n".join(problems))

    if args.symbols_root is not None:
        problems = check_symbols(args.repo_root, args.symbols_root, landed)
        if problems:
            raise SupportTableError(
                "Landed binaries without a Symbols~/ twin:\n" + "\n".join(problems))

    if not args.readme.is_file():
        raise SupportTableError(f"Missing {args.readme}")
    text = args.readme.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise SupportTableError(
            f"{args.readme} has no generated-table markers.\n"
            f"  Insert these two lines where the table belongs:\n    {BEGIN}\n    {END}")

    head, _, rest = text.partition(BEGIN)
    _, _, tail = rest.partition(END)
    updated = head + render(landed, args.report_root.name) + tail

    if updated == text:
        print(f"OK: the support table lists {len(landed)}/{len(PLATFORMS)} platform(s) "
              "and is up to date")
        return 0

    if args.check:
        raise SupportTableError(
            "The support table in the README is stale.\n"
            "  Fix: run native/scripts/gen_support_table.py without --check and commit the diff.\n"
            "  The table is derived from the binaries git tracks, so it cannot be\n"
            "  maintained by hand -- and therefore cannot silently go out of date.")

    args.readme.write_text(updated, encoding="utf-8")
    print(f"wrote the support table into {args.readme} "
          f"({len(landed)}/{len(PLATFORMS)} platform(s) shipped)")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except SupportTableError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
