#!/usr/bin/env python3
"""Generate the "supported platforms" table in the package README (decision #53).

Authoritative source: the binaries **tracked by git**, not the ones on disk.

That distinction is the whole point. Plugin binaries are currently gitignored
until a batch lands (#35), so a working tree that has just been built has a
macOS binary while a fresh clone has none. Keying off the filesystem would make
this table differ between a developer's machine and CI, and the CI diff would
be permanently red -- the same trap that the orphan-.meta rule fell into.

What git tracks is exactly what an adopter receives, so it is both stable and
the honest answer to "which platforms does this package ship?".

The table therefore cannot lie: it is derived from the artifacts themselves.
Nobody maintains a list by hand, so nobody can forget to update one (#53).

Also enforced here, because this script already walks the landed artifacts:

    every landed binary must have a CI-produced provenance file in `Report~/`.

A build-info file with `ci: null` was produced by someone's local build; it
records a dirty worktree and no run URL, so it has no provenance value at all
(#54). Landing one would leave a binary nobody can trace.

#65 moved those files out of `Plugins/` and into `Report~/<flattened>.json`,
which changes only where this gate looks -- **not what it can prove**. The
point of #54's "beside the binary" was never convenience; it was that
"binary landed, provenance did not" must have nowhere to hide. That survives
intact, because the expected file name is still computed from the binary's own
path (`gen_plugin_meta.report_name`). There is no hand-maintained mapping here
that could be quietly edited to make a missing file look present.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_plugin_meta import PLATFORMS, report_name  # noqa: E402  单一平台清单与拍平名推导


def _force_utf8_output() -> None:
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            reconfigure(encoding="utf-8")


_force_utf8_output()

BEGIN = "<!-- BEGIN supported-platforms (generated by native/scripts/gen_support_table.py) -->"
END = "<!-- END supported-platforms -->"

# Display metadata, keyed by the same relative paths as gen_plugin_meta.PLATFORMS.
# The keys are cross-checked against that map below, so the two cannot drift:
# adding a platform there without adding it here is a hard failure, not a
# silently missing table row.
DISPLAY = {
    "Windows/x86_64/datachannel_unity.dll": ("Windows", "x86_64", "Editor + Player"),
    "macOS/datachannel_unity.dylib": ("macOS", "universal (arm64 + x86_64)", "Editor + Player"),
    "Linux/x86_64/libdatachannel_unity.so": ("Linux", "x86_64", "Editor + Player"),
    "Android/arm64-v8a/libdatachannel_unity.so": ("Android", "arm64-v8a", "Player only"),
    "iOS/libdatachannel_unity.a": ("iOS", "arm64", "Player only"),
}


class SupportTableError(Exception):
    pass


def tracked_files(repo_root: Path, directory: Path) -> set[str]:
    """Paths git tracks under `directory`, relative to it.

    Called twice: once for `Plugins/` (which binaries shipped) and once for
    `Report~/` (which provenance files shipped). An untracked-but-present file
    counts as absent in both, which is the point -- what git tracks is exactly
    what an adopter receives.
    """
    rel = directory.resolve().relative_to(repo_root.resolve())
    proc = subprocess.run(["git", "-C", str(repo_root), "ls-files", str(rel)],
                          capture_output=True, text=True)
    if proc.returncode != 0:
        raise SupportTableError(
            f"git ls-files failed for {rel}, so what this package ships cannot be "
            "determined.\n"
            f"  {proc.stderr.strip()}\n"
            "  This script keys off what git tracks on purpose; guessing from the\n"
            "  filesystem would make the table differ between a built worktree and a\n"
            "  fresh clone.")
    prefix = str(rel).replace("\\", "/") + "/"
    return {line[len(prefix):] for line in proc.stdout.splitlines()
            if line.replace("\\", "/").startswith(prefix)}


def is_landed(rel: str, tracked: set[str]) -> bool:
    """Is this platform's artifact tracked by git?

    Every artifact is a single file today, so plain equality would do. The
    prefix branch stays because it once did not: macOS shipped a `.bundle`,
    a **directory**, and git tracks the files inside it rather than the
    directory itself -- exact matching silently reported "not landed" for
    macOS forever. The bundle is gone (see stage_plugin.py), but a directory
    artifact can come back (an iOS `.framework`, say), and this branch costs
    one line.
    """
    return rel in tracked or any(t.startswith(rel + "/") for t in tracked)


def check_build_info(tracked_reports: set[str], landed: list[str],
                     report_root: Path) -> list[str]:
    """Every landed binary needs a CI-produced provenance file in `Report~/`."""
    problems = []
    for rel in landed:
        # Derived from the binary's own path, so no list exists that could lie.
        name = report_name(Path(rel).parent.as_posix())
        if name not in tracked_reports:
            problems.append(f"  {rel}: no provenance file is tracked for it "
                            f"(expected {report_root.name}/{name})")
            continue
        path = report_root / name
        try:
            info = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            problems.append(f"  {name}: cannot be read as JSON ({exc})")
            continue
        ci = info.get("ci")
        if not ci:
            problems.append(
                f"  {name}: ci is null, so this came from a local build. "
                "Land the CI-produced file instead -- a local one records a dirty "
                "worktree and no run URL, so it has no provenance value.")
            continue
        if ci.get("event") == "pull_request":
            problems.append(
                f"  {name}: built by a `pull_request` run, so source.commit "
                f"({info.get('source', {}).get('commit', '?')[:9]}) is GitHub's synthetic "
                "merge ref -- that SHA stops existing once the PR is merged, and the "
                "binary becomes untraceable. Land artifacts from a push-to-main run or "
                "from plugins-matrix.yml (dispatch / schedule / release) instead.")
    return problems


def render(landed: list[str], report_dirname: str) -> str:
    """The table also names each platform's provenance file, for the same reason
    the platform rows are generated at all (#53): a hand-written "where is the
    build record for my platform" list is one more thing that goes stale the day
    a platform lands and nobody remembers to edit the README. The file name comes
    from the same `report_name` the gate uses, so the column cannot point at a
    file that is not the one being checked.
    """
    lines = [BEGIN, ""]
    if not landed:
        lines += [
            "This package currently ships **no platform binaries**.",
            "",
            "They land in batches, each after that platform passes CI plus a real-device",
            "smoke test. Building for any platform will stop with an explicit error rather",
            "than producing a player that fails at runtime.",
        ]
    else:
        lines += [
            "| Platform | Architecture | Loaded by | Build record |",
            "|---|---|---|---|",
        ]
        for rel in landed:
            name, arch, where = DISPLAY[rel]
            record = report_name(Path(rel).parent.as_posix())
            lines.append(f"| {name} | {arch} | {where} | `{report_dirname}/{record}` |")
        missing = [r for r in PLATFORMS if r not in landed]
        if missing:
            lines += ["", "Not shipped yet: "
                      + ", ".join(DISPLAY[r][0] + " " + DISPLAY[r][1] for r in missing)
                      + ". Building for those targets stops with an explicit error."]
    lines += ["", END]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate the supported-platforms table")
    ap.add_argument("--repo-root", required=True, type=Path)
    ap.add_argument("--plugin-root", required=True, type=Path)
    ap.add_argument("--report-root", required=True, type=Path,
                    help="Packages/datachannel-unity/Report~ -- where the provenance "
                         "files live since #65")
    ap.add_argument("--readme", required=True, type=Path)
    ap.add_argument("--check", action="store_true",
                    help="check only, never write; exit non-zero on any difference (for CI)")
    args = ap.parse_args()

    unknown = set(DISPLAY) ^ set(PLATFORMS)
    if unknown:
        raise SupportTableError(
            "DISPLAY and gen_plugin_meta.PLATFORMS disagree: " + ", ".join(sorted(unknown))
            + "\n  They must list exactly the same platforms. Adding one to the meta\n"
              "  generator without adding it here would silently drop a table row.")

    tracked = tracked_files(args.repo_root, args.plugin_root)
    landed = [rel for rel in PLATFORMS if is_landed(rel, tracked)]

    problems = check_build_info(tracked_files(args.repo_root, args.report_root),
                                landed, args.report_root)
    if problems:
        raise SupportTableError(
            "Landed binaries without usable provenance (#54):\n" + "\n".join(problems))

    if not args.readme.is_file():
        raise SupportTableError(f"Missing {args.readme}")
    text = args.readme.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise SupportTableError(
            f"{args.readme} has no generated-table markers.\n"
            f"  Insert these two lines where the table belongs:\n    {BEGIN}\n    {END}")

    head, _, rest = text.partition(BEGIN)
    _, _, tail = rest.partition(END)
    updated = head + render(landed, args.report_root.name) + tail

    if updated == text:
        print(f"OK: the support table lists {len(landed)}/{len(PLATFORMS)} platform(s) "
              "and is up to date")
        return 0

    if args.check:
        raise SupportTableError(
            "The support table in the README is stale.\n"
            "  Fix: run native/scripts/gen_support_table.py without --check and commit the diff.\n"
            "  The table is derived from the binaries git tracks, so it cannot be\n"
            "  maintained by hand -- and therefore cannot silently go out of date.")

    args.readme.write_text(updated, encoding="utf-8")
    print(f"wrote the support table into {args.readme} "
          f"({len(landed)}/{len(PLATFORMS)} platform(s) shipped)")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except SupportTableError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
