#!/usr/bin/env python3
"""iOS 静态归档合并 + 符号收窄（决议 #50 / #93；合并部分见 #97）。

管线：libtool -static <wrapper 归档 + 全部依赖归档>
      → ld -r -exported_symbols_list -all_load → ar crs <输出归档> → nm -u 自检

（**不是** `ar x`：归档内允许同名成员，按文件名解包会静默互相覆盖，见 step 1 的注释。）

**这是产物的唯一来源**：CMakeLists 构出的 libdatachannel_unity.a 是未收窄的，
本脚本输出的才是最终入库的 .a，也是 audit_plugin.py 要检查的那一份。

为什么依赖必须在这里显式合并（#97）：
    其它平台的产物是动态库，依赖在**链接期**被拉进去；iOS 是 STATIC，而
    **静态库没有链接期** —— target_link_libraries 只记录依赖关系，不复制代码。
    最初的版本只 ar x 了 wrapper 自己那一个归档，于是入库的 .a 是 107 KB、
    只含 wrapper、带 89 个未解析引用（32 个 rtc::*），而导出门禁**全绿**：
    dcu_* 二十个一个不少，crypto 符号一个不露（因为 mbedtls 压根没进来）。
    故障要到下游 Xcode 链接 UnityFramework 时才现形。
    step 4 的自检就是为这个装的：只数导出符号，永远看不出实现在不在。

为什么是独立脚本而不是并进 stage_plugin.py：
    stage 的语义是「复制产物到位」，收窄是前置的变换步骤，两者职责不同。
    形状与 audit_plugin.py 一致（POST_BUILD Python 脚本，由 CMake 调用）。

为什么 --symbols-list 找不到时硬失败：
    参照实现（unity-sqlcipher-net-openharmony/merge-static-libs.sh）在找不到
    符号列表时 fallback 到「简单合并、无符号控制」并正常退出 —— 正是 CONTRIBUTING
    第一原则点名的病。我们这一步必须硬失败。

ld -r 的语义（#47 实测确认）：
    -exported_symbols_list 只能降级（把 external → non-external），不能提升
    （把 hidden → external 会报 "cannot export hidden symbol"）。
    这对我们有效是因为白名单 = DCU_API 那一组，本来就是 default visible。
    副产品：多写一个名字会让 iOS 链接当场红，提供额外的一致性保证。
"""

from __future__ import annotations

import argparse
import pathlib
import re
import shutil
import subprocess
import sys


def _force_utf8_output() -> None:
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            reconfigure(encoding="utf-8")


_force_utf8_output()


class NarrowError(Exception):
    pass


# 打包后仍未解析 = 某个依赖没被合进来。只匹配**实现库**的命名空间/前缀，
# 不匹配 C++ 运行时与 libSystem（__ZNSt…、__Unwind_Resume、_memcpy 等）——
# 那些由 Xcode 在下游链接 UnityFramework 时提供，本来就该是未解析的。
IMPLEMENTATION_RE = re.compile(r"(?:^|_)(?:_ZN3rtc|_ZNK3rtc|juice_|mbedtls_|usrsctp_|srtp_)")


def run(cmd: list[str]) -> str:
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise NarrowError(
            f"Command failed (rc={proc.returncode}): {' '.join(cmd)}\n{proc.stderr.strip()}"
        )
    return proc.stdout


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Narrow an iOS static archive to only dcu_* symbols via ld -r"
    )
    ap.add_argument("--archive", required=True, type=pathlib.Path,
                    help="CMake-built .a (un-narrowed)")
    ap.add_argument("--out", required=True, type=pathlib.Path,
                    help="Output path for the narrowed .a (staged to Plugins/iOS/)")
    ap.add_argument("--symbols-list", required=True, type=pathlib.Path,
                    help="macos-exported-symbols.txt (generated by gen_exports.py)")
    ap.add_argument("--extra-archive", dest="extra_archives", action="append",
                    default=[], type=pathlib.Path, metavar="PATH",
                    help="Dependency .a to merge in (repeatable). Required on iOS: a STATIC "
                         "target has no link step, so dependencies are not pulled in for us.")
    ap.add_argument("--arch", default="arm64",
                    help="Target architecture (arm64)")
    ap.add_argument("--deployment-target", required=True,
                    help="iOS deployment target, e.g. 12.0")
    ap.add_argument("--sdk-version", required=True,
                    help="iPhoneOS SDK version, e.g. 26.5")
    ap.add_argument("--tmp-dir", required=True, type=pathlib.Path,
                    help="Scratch directory for .o files (cleared on each run)")
    args = ap.parse_args()

    # ── guards ──────────────────────────────────────────────────────────────
    if not args.archive.is_file():
        raise NarrowError(f"Archive does not exist: {args.archive}")

    # 找不到符号列表时硬失败，不 fallback 到无收窄的合并
    if not args.symbols_list.is_file():
        raise NarrowError(
            f"Symbols list does not exist: {args.symbols_list}\n"
            "  This file is generated by gen_exports.py at configure time.\n"
            "  This step will not fall back to unconstrained merging: that would make\n"
            "  'narrowing did not run' and 'narrowing ran and passed' look identical."
        )

    ar = shutil.which("ar")
    if not ar:
        raise NarrowError("Cannot find 'ar' — required to explode and repack the archive.")

    # ── prepare tmp dir ──────────────────────────────────────────────────────
    tmp = args.tmp_dir
    if tmp.exists():
        shutil.rmtree(tmp)
    tmp.mkdir(parents=True)

    # ── step 1: 合并 wrapper 与全部依赖归档 ──────────────────────────────────
    # 缺了依赖那一半，产物会是一个只含 wrapper、带 89 个未解析引用的 .a ——
    # 它能过导出门禁（dcu_* 全在、crypto 一个不露），只在下游 Xcode 链接
    # UnityFramework 时才炸。
    #
    # 用 libtool -static 而不是 `ar x` 再 `ld -r`：**归档内允许同名成员**，
    # 而 `ar x` 按文件名解包，同名的会互相静默覆盖。libdatachannel-static.a
    # 就有 7 个同名成员（peerconnection.cpp.o 等各出现两次，63 个成员只有
    # 56 个不同的名字），其中一份定义符号、另一份只引用它。解包会留下引用
    # 的那份，于是 rtc::PeerConnection::onIceStateChange 这类符号在合并结果
    # 里仍然是 U —— 一个更隐蔽的、只丢一部分实现的版本。
    for extra in args.extra_archives:
        if not extra.is_file():
            raise NarrowError(
                f"Dependency archive does not exist: {extra}\n"
                "  iOS ships a STATIC library, which has no link step: target_link_libraries\n"
                "  records the dependency but never copies its code in. Every dependency must\n"
                "  be merged here explicitly, or the shipped .a is missing its implementation."
            )

    libtool = shutil.which("libtool")
    if not libtool:
        raise NarrowError("Cannot find 'libtool' — required to merge the dependency archives.")

    merged = tmp / "merged.a"
    inputs = [args.archive] + list(args.extra_archives)
    merge_proc = subprocess.run(
        [libtool, "-static", "-o", str(merged)] + [str(p.resolve()) for p in inputs],
        capture_output=True, text=True,
    )
    if merge_proc.returncode != 0:
        raise NarrowError(
            f"libtool -static failed (rc={merge_proc.returncode}):\n{merge_proc.stderr.strip()}"
        )
    if not merged.is_file():
        raise NarrowError("libtool -static reported success but produced no archive.")
    print(f"==> merged {len(inputs)} archive(s) → {merged.name} "
          f"({merged.stat().st_size} bytes)")

    # ── step 2: ld -r with symbol list ──────────────────────────────────────
    combined_o = tmp / "combined.o"
    ld_cmd = [
        "xcrun", "-sdk", "iphoneos", "ld",
        "-r",
        "-arch", args.arch,
        "-platform_version", "ios",
        args.deployment_target,
        args.sdk_version,
        "-exported_symbols_list", str(args.symbols_list),
        # 归档作为输入时，ld 默认只拉「被引用到的」成员。这里要的是全部：
        # 少拉的那部分是运行期才走到的实现，缺了它编译期一样安静。
        "-all_load",
        "-o", str(combined_o),
        str(merged),
    ]

    proc2 = subprocess.run(ld_cmd, capture_output=True, text=True)
    if proc2.returncode != 0:
        raise NarrowError(
            f"ld -r failed (rc={proc2.returncode}):\n{proc2.stderr.strip()}\n\n"
            "  Typical causes:\n"
            "    - A symbol in --symbols-list is hidden (DCU_API missing on that function)\n"
            "    - A symbol in --symbols-list does not exist in any .o\n"
            "  See #47 / #50 for the design constraint: -exported_symbols_list can only\n"
            "  demote, never promote. The whitelist must exactly equal the DCU_API set."
        )
    print(f"==> ld -r OK → {combined_o.name}")

    # ── step 3: repack into .a ───────────────────────────────────────────────
    args.out.parent.mkdir(parents=True, exist_ok=True)
    if args.out.exists():
        args.out.unlink()
    proc3 = subprocess.run(
        [ar, "crs", str(args.out), str(combined_o)],
        capture_output=True, text=True
    )
    if proc3.returncode != 0:
        raise NarrowError(
            f"ar crs failed (rc={proc3.returncode}):\n{proc3.stderr.strip()}"
        )
    print(f"==> packed → {args.out}")

    # ── step 4: 自检 —— 实现必须真的在里面 ──────────────────────────────────
    # 只数导出符号看不出这个：一个只含 wrapper 的归档，dcu_* 二十个一个不少。
    # 差别全在未解析引用上，所以这里问的是「实现有没有跟着进来」。
    nm = shutil.which("nm")
    if not nm:
        raise NarrowError("Cannot find 'nm' — required to verify the packed archive.")
    undefined = {
        line.strip().split()[-1]
        for line in run([nm, "-u", str(args.out)]).splitlines()
        if line.strip() and not line.strip().endswith(":")
    }
    missing = sorted(s for s in undefined if IMPLEMENTATION_RE.search(s))
    if missing:
        raise NarrowError(
            "The packed archive still has undefined implementation symbols — a dependency\n"
            "was not merged in:\n"
            + "".join(f"    {s}\n" for s in missing[:12])
            + (f"    … and {len(missing) - 12} more\n" if len(missing) > 12 else "")
            + "\n  Pass every dependency archive with --extra-archive. iOS ships a STATIC\n"
              "  library, which has no link step, so nothing pulls these in automatically.\n"
              "  Exported-symbol checks cannot catch this: an archive holding only the\n"
              "  wrapper still exports all of dcu_*."
        )
    print(f"==> self-check: no undefined implementation symbols ({len(undefined)} extern refs, all toolchain)")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except NarrowError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
