#!/usr/bin/env python3
"""iOS 静态归档符号收窄（决议 #50 / #93）。

管线：ar x <归档> → ld -r -exported_symbols_list → ar crs <输出归档>

**这是产物的唯一来源**：CMakeLists 构出的 libdatachannel_unity.a 是未收窄的，
本脚本输出的才是最终入库的 .a，也是 audit_plugin.py 要检查的那一份。

为什么是独立脚本而不是并进 stage_plugin.py：
    stage 的语义是「复制产物到位」，收窄是前置的变换步骤，两者职责不同。
    形状与 audit_plugin.py 一致（POST_BUILD Python 脚本，由 CMake 调用）。

为什么 --symbols-list 找不到时硬失败：
    参照实现（unity-sqlcipher-net-openharmony/merge-static-libs.sh）在找不到
    符号列表时 fallback 到「简单合并、无符号控制」并正常退出 —— 正是 CONTRIBUTING
    第一原则点名的病。我们这一步必须硬失败。

ld -r 的语义（#47 实测确认）：
    -exported_symbols_list 只能降级（把 external → non-external），不能提升
    （把 hidden → external 会报 "cannot export hidden symbol"）。
    这对我们有效是因为白名单 = DCU_API 那一组，本来就是 default visible。
    副产品：多写一个名字会让 iOS 链接当场红，提供额外的一致性保证。
"""

from __future__ import annotations

import argparse
import pathlib
import shutil
import subprocess
import sys


def _force_utf8_output() -> None:
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            reconfigure(encoding="utf-8")


_force_utf8_output()


class NarrowError(Exception):
    pass


def run(cmd: list[str]) -> str:
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise NarrowError(
            f"Command failed (rc={proc.returncode}): {' '.join(cmd)}\n{proc.stderr.strip()}"
        )
    return proc.stdout


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Narrow an iOS static archive to only dcu_* symbols via ld -r"
    )
    ap.add_argument("--archive", required=True, type=pathlib.Path,
                    help="CMake-built .a (un-narrowed)")
    ap.add_argument("--out", required=True, type=pathlib.Path,
                    help="Output path for the narrowed .a (staged to Plugins/iOS/)")
    ap.add_argument("--symbols-list", required=True, type=pathlib.Path,
                    help="macos-exported-symbols.txt (generated by gen_exports.py)")
    ap.add_argument("--arch", default="arm64",
                    help="Target architecture (arm64)")
    ap.add_argument("--deployment-target", required=True,
                    help="iOS deployment target, e.g. 12.0")
    ap.add_argument("--sdk-version", required=True,
                    help="iPhoneOS SDK version, e.g. 26.5")
    ap.add_argument("--tmp-dir", required=True, type=pathlib.Path,
                    help="Scratch directory for .o files (cleared on each run)")
    args = ap.parse_args()

    # ── guards ──────────────────────────────────────────────────────────────
    if not args.archive.is_file():
        raise NarrowError(f"Archive does not exist: {args.archive}")

    # 找不到符号列表时硬失败，不 fallback 到无收窄的合并
    if not args.symbols_list.is_file():
        raise NarrowError(
            f"Symbols list does not exist: {args.symbols_list}\n"
            "  This file is generated by gen_exports.py at configure time.\n"
            "  This step will not fall back to unconstrained merging: that would make\n"
            "  'narrowing did not run' and 'narrowing ran and passed' look identical."
        )

    ar = shutil.which("ar")
    if not ar:
        raise NarrowError("Cannot find 'ar' — required to explode and repack the archive.")

    # ── prepare tmp dir ──────────────────────────────────────────────────────
    tmp = args.tmp_dir
    if tmp.exists():
        shutil.rmtree(tmp)
    tmp.mkdir(parents=True)

    # ── step 1: explode archive → .o files ──────────────────────────────────
    # ar x writes to cwd, so run it from tmp
    import subprocess as _sp
    proc = _sp.run(
        [ar, "x", str(args.archive.resolve())],
        capture_output=True, text=True, cwd=str(tmp)
    )
    if proc.returncode != 0:
        raise NarrowError(
            f"ar x failed (rc={proc.returncode}):\n{proc.stderr.strip()}"
        )
    objects = sorted(tmp.glob("*.o"))
    if not objects:
        raise NarrowError(
            f"ar x produced no .o files from {args.archive.name}.\n"
            "  An empty archive means the narrowing check never ran — treating as failure\n"
            "  so 'never ran' and 'ran and passed' are distinguishable."
        )
    print(f"==> exploded {args.archive.name}: {len(objects)} object(s)")

    # ── step 2: ld -r with symbol list ──────────────────────────────────────
    combined_o = tmp / "combined.o"
    ld_cmd = [
        "xcrun", "-sdk", "iphoneos", "ld",
        "-r",
        "-arch", args.arch,
        "-platform_version", "ios",
        args.deployment_target,
        args.sdk_version,
        "-exported_symbols_list", str(args.symbols_list),
        "-o", str(combined_o),
    ] + [str(o) for o in objects]

    proc2 = _sp.run(ld_cmd, capture_output=True, text=True)
    if proc2.returncode != 0:
        raise NarrowError(
            f"ld -r failed (rc={proc2.returncode}):\n{proc2.stderr.strip()}\n\n"
            "  Typical causes:\n"
            "    - A symbol in --symbols-list is hidden (DCU_API missing on that function)\n"
            "    - A symbol in --symbols-list does not exist in any .o\n"
            "  See #47 / #50 for the design constraint: -exported_symbols_list can only\n"
            "  demote, never promote. The whitelist must exactly equal the DCU_API set."
        )
    print(f"==> ld -r OK → {combined_o.name}")

    # ── step 3: repack into .a ───────────────────────────────────────────────
    args.out.parent.mkdir(parents=True, exist_ok=True)
    if args.out.exists():
        args.out.unlink()
    proc3 = _sp.run(
        [ar, "crs", str(args.out), str(combined_o)],
        capture_output=True, text=True
    )
    if proc3.returncode != 0:
        raise NarrowError(
            f"ar crs failed (rc={proc3.returncode}):\n{proc3.stderr.strip()}"
        )
    print(f"==> packed → {args.out}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except NarrowError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
